name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # lets you run it manually from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend /health (120s timeout)
        run: |
          curl -L --max-time 120 -fsS https://mini-rag-spzd.onrender.com/health >/dev/null || true